### PR TITLE
Fixed sonar warnings.

### PR DESCRIPTION
**Pull request by javadev**

### CODE REVIEW

**Comment by javadev** [comment]
@MehmetAzizYirik this pull request will fix all sonar warnings.

**Comment by javadev** [comment]
It will fix these sonar warnings

image

**Comment by MehmetAzizYirik** [comment]
> It will fix these sonar warnings
> 
> image

@javadev did you fix the issues ? should I merge them or wait ?

**Comment by javadev** [comment]
@MehmetAzizYirik this pull request will fix issues.

**Pull request merged**
