### PR TITLE
Reused SDFWriter from CDK.

### PR DESCRIPTION
**Pull request by javadev**

### CODE REVIEW

**Comment by javadev** [comment]
@steinbeck these changes allows to reuse class from cdk.

**Comment by javadev** [comment]
➕

**Comment by javadev** [comment]
It will be closed on January 15.

**Comment by MehmetAzizYirik** [comment]
> It will be closed on January 15.

@javadev Thanks. I am going to merge just this request, since it is not that much different than the version integrated into CDK. As I mentioned earlier, After the integration to the CDK, the software is in the good hands and I keep my repository as just part of my PhD. So I will try not to do any changes here.

**Pull request merged**
